feat: get clam price from dyst
OtterClam/otter-subgraph pull request #14
Opened 2022-07-07 07:17 UTC by pyc92

2022-07-12 12:51 UTC, abtheo approved these changes
Awesome, code is much cleaner! New functionality looks like it works but it's always helpful to have a development subgraph synced for testing before we deploy to main. I'll start syncing it on my dev graph here - https://thegraph.com/hosted-service/subgraph/abtheo/otter-development?pending

2022-07-12 12:59 UTC, abtheo requested changes
Ah, unfortunately looks like it fails to sync - 
![image](https://user-images.githubusercontent.com/24249418/178495744-a38e0fad-5e20-47ac-8dbf-b1cd939b9fe0.png)

```
Subgraph error 1/3, code: SubgraphSyncingFailure, error: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 434, column 7, with message: Call reverted, probably because an `assert` or `require` in the contract failed, consider using `try_decimals` to handle this in the mapping. wasm backtrace: 0: 0x6247 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x66df - <unknown>!src/utils/Price/findTokenPrice 2: 0x6b0b - <unknown>!src/utils/Price/getClamUsdRate 3: 0x6fa5 - <unknown>!src/utils/Price/getPairUSD 4: 0x77ae - <unknown>!src/utils/ProtocolMetrics/setTreasuryAssetMarketValues 5: 0x9dff - <unknown>!src/utils/ProtocolMetrics/updateProtocolMetrics 6: 0xa7dc - <unknown>!src/StakedOtterClamERC20V2/handleTransfer in handler `handleTransfer` at block #21593528 (9caf2ced725c8946caf9f28c81448fb4f6322981ee37110d7b67082a84ac34bf), block_hash:
```

2022-07-14 06:50 UTC, pyc92 commented
@abtheo  this one is still work in progress, I will fix it after we release staking v2.

2022-07-18 10:47 UTC, abtheo commented on src/utils/Price.ts
> +    rate = findTokenPrice(quickSwap, CLAM_ERC20, USDPLUS_ERC20)
Ah, I think I found the issue 😁

Before we moved to Dystopia, our liquidity pool was CLAM-MAI, not CLAM-USD+. 

`rate = findTokenPrice(quickSwap, CLAM_ERC20, USDPLUS_ERC20)` ==> `rate = findTokenPrice(quickSwap, CLAM_ERC20, MAI_ERC20)`

I am currently working on a large update for the Graph, and I will merge this PR into my branch. I'll fix this issue as well. 👍

2022-07-18 14:51 UTC, otterclamking commented on src/utils/Price.ts
> +    rate = findTokenPrice(quickSwap, CLAM_ERC20, USDPLUS_ERC20)
Great! Thank you @abtheo

2022-07-18 14:51 UTC, closed without merging